#!/usr/bin/env python3
"""
One-command production deployment script for mkindayzir.

Supports three deployment modes:
- personal: SQLite, single user, no Docker required
- team: PostgreSQL, multi-user, Docker required
- enterprise: Full features, PostgreSQL, Docker required
"""

import argparse
import base64
import json
import os
import secrets
import socket
import subprocess
import sys
import time
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path


# ─── ANSI Colors ───────────────────────────────────────────────────────────────

class Colors:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    MAGENTA = "\033[95m"
    CYAN = "\033[96m"
    WHITE = "\033[97m"

    @classmethod
    def ok(cls, text: str) -> str:
        return f"{cls.GREEN}{text}{cls.RESET}"

    @classmethod
    def err(cls, text: str) -> str:
        return f"{cls.RED}{text}{cls.RESET}"

    @classmethod
    def warn(cls, text: str) -> str:
        return f"{cls.YELLOW}{text}{cls.RESET}"

    @classmethod
    def info(cls, text: str) -> str:
        return f"{cls.CYAN}{text}{cls.RESET}"


# ─── Helpers ───────────────────────────────────────────────────────────────────

def generate_secret(bytes_len: int = 32) -> str:
    """Generate a cryptographically secure random secret, base64 encoded."""
    return base64.urlsafe_b64encode(secrets.token_bytes(bytes_len)).decode("utf-8")


def project_root() -> Path:
    """Return the mkindayzir project root directory."""
    return Path(__file__).resolve().parent.parent


def run_command(cmd: list[str], check: bool = True, capture: bool = True, env: dict | None = None) -> subprocess.CompletedProcess:
    """Run a shell command with optional env overrides."""
    merged_env = {**os.environ}
    if env:
        merged_env.update(env)
    return subprocess.run(
        cmd,
        capture_output=capture,
        text=True,
        check=check,
        env=merged_env,
    )


def command_exists(cmd: str) -> bool:
    """Check if a command is available on PATH."""
    result = subprocess.run(["which", cmd], capture_output=True)
    return result.returncode == 0


def print_banner(mode: str, domain: str) -> None:
    banner = f"""
{Colors.BOLD}{Colors.CYAN}
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║   {Colors.WHITE}██╗  ██╗██╗███╗   ███╗██████╗ ██╗     ██████╗ ██╗{Colors.CYAN}   ║
║   {Colors.WHITE}██║ ██╔╝██║████╗ ████║██╔══██╗██║     ██╔══██╗██║{Colors.CYAN}   ║
║   {Colors.WHITE}█████╔╝ ██║██╔████╔██║██████╔╝██║     ██║  ██║██║{Colors.CYAN}   ║
║   {Colors.WHITE}██╔═██╗ ██║██║╚██╔╝██║██╔══██╗██║     ██║  ██║██║{Colors.CYAN}   ║
║   {Colors.WHITE}██║  ██╗██║██║ ╚═╝ ██║██║  ██║███████╗██████╔╝██║{Colors.CYAN}   ║
║   {Colors.WHITE}╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝{Colors.CYAN}   ║
║                                                              ║
║   {Colors.GREEN}Easy Install Script{Colors.CYAN}                                         ║
║   Mode: {Colors.WHITE}{mode.upper():<10}{Colors.CYAN}  Domain: {Colors.WHITE}{domain:<20}{Colors.CYAN}║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
{Colors.RESET}"""
    print(banner)


# ─── Core Functions ────────────────────────────────────────────────────────────

def write_env(mode: str, domain: str, email: str, db_password: str) -> Path:
    """Write .env file in the project root with deployment configuration."""
    root = project_root()
    env_path = root / ".env"

    session_secret = generate_secret()
    encryption_key = generate_secret()

    domain_url = domain if domain.startswith("http") else f"https://{domain}"
    if mode == "personal":
        domain_url = "http://localhost:3000"

    db_provider = "sqlite" if mode == "personal" else "postgresql"
    data_dir = "./data" if mode == "personal" else "/app/data"

    if db_provider == "sqlite":
        db_url = f"file:{data_dir}/mkindayzir.db"
    else:
        db_url = f"postgresql://mkindayzir:{db_password}@db:5432/mkindayzir"

    auto_login = "true" if mode == "personal" else "false"
    registration_enabled = "false" if mode == "personal" else "true"
    max_users = "1" if mode == "personal" else "0"

    env_content = f"""# Auto-generated by easy-install.py on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
MKINDAYZIR_MODE={mode}
AUTO_LOGIN={auto_login}
REGISTRATION_ENABLED={registration_enabled}
MAX_USERS={max_users}

# Database
DATABASE_PROVIDER={db_provider}
DATABASE_URL={db_url}
DATA_DIR={data_dir}

# Security
SESSION_SECRET={session_secret}
ENCRYPTION_KEY={encryption_key}
SESSION_MAX_AGE=86400
BCRYPT_ROUNDS=12

# Application
NODE_ENV=production
BASE_URL={domain_url}
PORT=3000
PYTHON_AI_URL=http://mkindayzir-ai:8000

# Email
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=noreply@{domain if domain else "mkindayzir.local"}

# Logging
LOG_LEVEL=info
LOG_FORMAT=json

# File Storage
UPLOAD_DIR={data_dir}/uploads
MAX_UPLOAD_SIZE=26214400
BACKUP_DIR={data_dir}/backups
"""

    env_path.write_text(env_content)
    print(Colors.ok(f"✓ Written .env to {env_path}"))
    return env_path


def check_prerequisites(mode: str) -> None:
    """Verify system prerequisites based on deployment mode."""
    print(Colors.header("CHECKING PREREQUISITES"))

    errors = []

    # Python check
    if sys.version_info < (3, 11):
        errors.append(f"Python 3.11+ required, found {sys.version}")

    # Docker-dependent modes
    if mode in ("team", "enterprise"):
        if not command_exists("docker"):
            errors.append("Docker is not installed. Install from https://docs.docker.com/get-docker/")
        if not command_exists("docker"):
            errors.append("docker compose is not available. Install Docker Compose plugin.")

        # Verify docker daemon is running
        try:
            run_command(["docker", "info"], capture=True)
        except subprocess.CalledProcessError:
            errors.append("Docker daemon is not running. Start Docker and try again.")

    if errors:
        for e in errors:
            print(Colors.err(f"✗ {e}"))
        print(Colors.err("\nPrerequisites check failed. Please fix the above issues and retry."))
        sys.exit(1)

    print(Colors.ok("✓ All prerequisites satisfied"))


def deploy_personal(domain: str, email: str) -> None:
    """Deploy in personal (SQLite, single-user, no Docker) mode."""
    print(Colors.header("DEPLOYING PERSONAL MODE"))

    root = project_root()
    print(Colors.info(f"Project root: {root}"))

    # Create data directories
    data_dir = root / "data"
    for subdir in ("uploads", "backups"):
        (data_dir / subdir).mkdir(parents=True, exist_ok=True)
    print(Colors.ok(f"✓ Created data directories at {data_dir}"))

    # Check if package.json exists
    pkg_json = root / "package.json"
    if not pkg_json.exists():
        print(Colors.err(f"✗ package.json not found at {pkg_json}"))
        sys.exit(1)

    # Check if pnpm is available
    pnpm_available = command_exists("pnpm")
    npm_available = command_exists("npm")
    pkg_manager = "pnpm" if pnpm_available else ("npm" if npm_available else None)

    if not pkg_manager:
        print(Colors.warn("Neither pnpm nor npm found. Please install one."))

    print(Colors.header("PERSONAL MODE SETUP COMPLETE"))
    print(Colors.ok("✓ Configuration generated"))
    print(Colors.info("\nNext steps:\n"))

    if pkg_manager:
        print(f"  {Colors.BOLD}1.{Colors.RESET} Install dependencies:")
        print(f"     {Colors.CYAN}{pkg_manager} install{Colors.RESET}")
        print(f"\n  {Colors.BOLD}2.{Colors.RESET} Run database migrations:")
        print(f"     {Colors.CYAN}{pkg_manager} prisma generate && {pkg_manager} prisma migrate deploy{Colors.RESET}")
        print(f"\n  {Colors.BOLD}3.{Colors.RESET} Start development server:")
        print(f"     {Colors.CYAN}{pkg_manager} dev{Colors.RESET}")
    else:
        print(f"  {Colors.BOLD}1.{Colors.RESET} Install pnpm: https://pnpm.io/installation")
        print(f"  {Colors.BOLD}2.{Colors.RESET} Install dependencies: {Colors.CYAN}pnpm install{Colors.RESET}")
        print(f"  {Colors.BOLD}3.{Colors.RESET} Generate Prisma client: {Colors.CYAN}pnpm prisma generate{Colors.RESET}")
        print(f"  {Colors.BOLD}4.{Colors.RESET} Run migrations: {Colors.CYAN}pnpm prisma migrate deploy{Colors.RESET}")
        print(f"  {Colors.BOLD}5.{Colors.RESET} Start development server: {Colors.CYAN}pnpm dev{Colors.RESET}")

    print(f"\n  {Colors.BOLD}Alternative:{Colors.RESET} Install as a CLI tool:")
    print(f"     {Colors.CYAN}npm install -g mkindayzir{Colors.RESET}")
    print(f"     {Colors.CYAN}mkindayzir start{Colors.RESET}")

    print(Colors.header("ACCESS INFORMATION"))
    print(f"  {Colors.BOLD}URL:{Colors.RESET}       http://localhost:3000")
    print(f"  {Colors.BOLD}Email:{Colors.RESET}     {email}")
    print(f"  {Colors.BOLD}Default Password:{Colors.RESET} Set during first-run setup wizard")
    print(f"  {Colors.BOLD}Mode:{Colors.RESET}      Personal (SQLite, single-user)")
    print()


def docker_compose_files(mode: str) -> tuple[Path, str | None]:
    """Return the compose file path and profile for a given mode."""
    root = project_root()

    # Check for docker/ directory first (preferred)
    docker_dir = root / "docker"
    if docker_dir.is_dir():
        if mode == "enterprise":
            return (docker_dir / "docker-compose.prod.yml", "enterprise")
        elif mode == "team":
            return (docker_dir / "docker-compose.prod.yml", "team")
    else:
        # Fall back to project root compose files
        if mode == "enterprise":
            return (root / "docker-compose.yml", "enterprise")
        elif mode == "team":
            return (root / "docker-compose.yml", "team")

    return (root / "docker-compose.yml", None)


def deploy_docker(mode: str, domain: str, email: str, db_password: str) -> None:
    """Deploy using Docker Compose (team or enterprise mode)."""
    print(Colors.header(f"DEPLOYING {mode.upper()} MODE (Docker)"))

    root = project_root()
    compose_file, profile = docker_compose_files(mode)

    if not compose_file.exists():
        print(Colors.err(f"Docker compose file not found: {compose_file}"))
        print(Colors.warn("Ensure docker-compose.yml exists in project root or docker/ directory."))
        sys.exit(1)

    print(Colors.info(f"Compose file: {compose_file}"))
    if profile:
        print(Colors.info(f"Profile: {profile}"))

    env_path = write_env(mode, domain, email, db_password)

    # Prepare docker compose command
    compose_cmd = ["docker", "compose", "-f", str(compose_file)]
    if profile:
        compose_cmd += ["--profile", profile]

    # Create volumes if needed
    print(Colors.info("Ensuring Docker volumes exist..."))
    run_command(compose_cmd + ["up", "-d", "--create-volumes"], check=False)

    # Pull images
    print(Colors.info("Pulling Docker images..."))
    result = run_command(compose_cmd + ["pull"], check=False)
    if result.returncode != 0:
        print(Colors.warn(f"Image pull had issues (will attempt build instead): {result.stderr[:200]}"))

    # Build images (if Dockerfile exists locally)
    print(Colors.info("Building images..."))
    result = run_command(compose_cmd + ["build"], check=False)
    if result.returncode != 0:
        print(Colors.err(f"Docker build failed:\n{result.stderr}"))
        sys.exit(1)
    print(Colors.ok("Images built successfully"))

    # Start services
    print(Colors.info("Starting services..."))
    result = run_command(compose_cmd + ["up", "-d"], check=False)
    if result.returncode != 0:
        print(Colors.err(f"docker compose up failed:\n{result.stderr}"))
        sys.exit(1)
    print(Colors.ok("Services started"))

    # Wait for health
    wait_for_health(compose_cmd)

    # Run migrations
    run_migrations(compose_cmd)

    # Create admin user
    create_admin(domain, email, mode)

    # Determine URL
    if domain:
        url = domain if domain.startswith("http") else f"https://{domain}"
    else:
        url = "http://localhost:3000"

    print(Colors.header("DEPLOYMENT COMPLETE"))
    print(Colors.ok(f"{mode.capitalize()} mode deployed successfully"))
    print()
    print(f"  {Colors.BOLD}URL:{Colors.RESET}       {Colors.UNDERLINE}{url}{Colors.RESET}")
    print(f"  {Colors.BOLD}Email:{Colors.RESET}     {email}")
    print(f"  {Colors.BOLD}Password:{Colors.RESET}  Set during first login / setup wizard")
    print(f"  {Colors.BOLD}Mode:{Colors.RESET}      {mode.capitalize()}")
    print()
    print(Colors.info("Services:"))
    print(f"  Frontend:  {Colors.CYAN}http://localhost:3000{Colors.RESET}")
    print(f"  Backend:   {Colors.CYAN}http://localhost:8000{Colors.RESET}")
    print(f"  Database:  {Colors.CYAN}PostgreSQL (via Docker){Colors.RESET}")
    print()
    print(Colors.info("Management commands:"))
    print(f"  View logs:     {Colors.CYAN}docker compose -f {compose_file} {'--profile ' + profile + ' ' if profile else ''}logs -f{Colors.RESET}")
    print(f"  Stop:          {Colors.CYAN}docker compose -f {compose_file} {'--profile ' + profile + ' ' if profile else ''}down{Colors.RESET}")
    print(f"  Restart:       {Colors.CYAN}docker compose -f {compose_file} {'--profile ' + profile + ' ' if profile else ''}restart{Colors.RESET}")
    print()


def wait_for_health(compose_cmd: list[str], timeout: int = 300) -> None:
    """Wait for all services to become healthy."""
    print(Colors.header("WAITING FOR HEALTH CHECK"))

    start = time.time()
    all_healthy = False

    while time.time() - start < timeout:
        try:
            req = urllib.request.Request("http://localhost:3000/api/health")
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 200:
                    all_healthy = True
                    break
        except (urllib.error.URLError, ConnectionRefusedError, TimeoutError, OSError):
            pass

        elapsed = int(time.time() - start)
        sys.stdout.write(f"\r{Colors.DIM}Waiting for services... {elapsed}s elapsed{Colors.RESET}")
        sys.stdout.flush()
        time.sleep(5)

    print()
    if all_healthy:
        print(Colors.ok("All services healthy"))
    else:
        print(Colors.warn("Health check timed out -- services may still be starting."))
        print(Colors.info("Check status with: docker compose ps"))


def run_migrations(compose_cmd: list[str]) -> None:
    """Run Alembic database migrations via docker compose exec."""
    print(Colors.header("RUNNING DATABASE MIGRATIONS"))

    # Run migrations using the backend service
    result = run_command(
        compose_cmd + ["exec", "-T", "backend", "alembic", "upgrade", "head"],
        check=False,
    )

    if result.returncode == 0:
        print(Colors.ok("Migrations applied successfully"))
        return

    # Fallback: try prisma migrate deploy
    print(Colors.warn("Alembic migration failed, trying Prisma deploy..."))
    result = run_command(
        compose_cmd + ["exec", "-T", "mkindayzir", "pnpm", "prisma", "migrate", "deploy"],
        check=False,
    )

    if result.returncode == 0:
        print(Colors.ok("Prisma migrations applied successfully"))
    else:
        print(Colors.warn(f"Migration step encountered issues:\n{result.stderr[:500]}"))
        print(Colors.info("You may need to run migrations manually after deployment."))


def create_admin(domain: str, email: str, mode: str) -> str | None:
    """Create admin user via the /api/setup endpoint."""
    print(Colors.header("CREATING ADMIN USER"))

    admin_password = generate_secret(16)
    admin_display_name = email.split("@")[0].replace(".", " ").replace("-", " ").title()
    admin_display_name = "".join(c for c in admin_display_name if c.isalpha() or c == " ").strip() or "Admin"

    payload = json.dumps({
        "mode": mode,
        "email": email,
        "displayName": admin_display_name,
        "password": admin_password,
        "confirmPassword": admin_password,
    }).encode("utf-8")

    req = urllib.request.Request(
        "http://localhost:3000/api/setup",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            print(Colors.ok("Admin user created successfully"))
            print(f"\n  {Colors.BOLD}Email:{Colors.RESET}     {email}")
            print(f"  {Colors.BOLD}Password:{Colors.RESET}  {admin_password}")
            print(f"  {Colors.BOLD}Name:{Colors.RESET}      {admin_display_name}")
            print(f"\n  {Colors.YELLOW}Save this password -- it won't be shown again!{Colors.RESET}")
            print()
            return admin_password
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8") if e.fp else ""
        if "ALREADY_SETUP" in body or e.code == 400:
            print(Colors.warn("Setup already completed -- admin user may already exist."))
            return None
        print(Colors.err(f"Failed to create admin user (HTTP {e.code}): {body[:300]}"))
        return None
    except Exception as e:
        print(Colors.err(f"Error creating admin user: {e}"))
        return None


# ─── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="easy-install.py",
        description="One-command production deployment for mkindayzir",
    )
    parser.add_argument(
        "action",
        choices=["deploy"],
        help="Action to perform (currently only 'deploy' is supported)",
    )
    parser.add_argument(
        "--mode",
        choices=["personal", "team", "enterprise"],
        required=True,
        help="Deployment mode: personal (SQLite, no Docker), team (PostgreSQL, Docker), enterprise (full features, Docker)",
    )
    parser.add_argument(
        "--domain",
        default="",
        help="Domain name for the application (e.g. ops.mycompany.local)",
    )
    parser.add_argument(
        "--email",
        required=True,
        help="Admin email address",
    )
    parser.add_argument(
        "--db-password",
        default=None,
        help="Database password (for Docker modes). Auto-generated if not provided.",
    )

    args = parser.parse_args()

    if args.action != "deploy":
        print(Colors.err("Only 'deploy' action is currently supported."))
        sys.exit(1)

    mode = args.mode
    domain = args.domain
    email = args.email
    db_password = args.db_password or generate_secret(24)

    print_banner(mode, domain)
    print(Colors.info(f"Deployment mode: {mode}"))
    print(Colors.info(f"Admin email:     {email}"))
    print(Colors.info(f"Domain:          {domain or '(default localhost)'}"))
    print()

    check_prerequisites(mode)

    if mode == "personal":
        deploy_personal(domain, email)
    else:
        deploy_docker(mode, domain, email, db_password)


if __name__ == "__main__":
    main()
