#!/usr/bin/env tsx
/**
 * First-run setup script for Mkindayzir
 * Creates data directories, generates secrets, and seeds initial data
 */

import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { randomBytes } from "crypto";

function generateSecret(length: number): string {
  return randomBytes(length).toString("hex");
}

function main() {
  const dataDir = process.env.DATA_DIR || "./data";
  const uploadsDir = join(dataDir, "uploads");
  const backupsDir = join(dataDir, "backups");

  // Create directories
  [dataDir, uploadsDir, backupsDir].forEach((dir) => {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      console.log(`Created directory: ${dir}`);
    }
  });

  // Check .env
  const envPath = join(process.cwd(), ".env");
  if (!existsSync(envPath)) {
    const envContent = `# Auto-generated by setup script
NODE_ENV=development
PORT=3000
BASE_URL=http://localhost:3000
MKINDAYZIR_MODE=personal
DATABASE_PROVIDER=sqlite
DATABASE_URL=file:./data/mkindayzir.db
DATA_DIR=./data
SESSION_SECRET=${generateSecret(32)}
ENCRYPTION_KEY=${generateSecret(16)}
SESSION_MAX_AGE=86400
BCRYPT_ROUNDS=12
AUTO_LOGIN=false
MAX_UPLOAD_SIZE=26214400
LOG_LEVEL=info
LOG_FORMAT=json
`;

    writeFileSync(envPath, envContent);
    console.log("Created .env with generated secrets");
  }

  console.log("Setup complete!");
  console.log("Next steps:");
  console.log("  1. pnpm install");
  console.log("  2. pnpm prisma:generate");
  console.log("  3. pnpm prisma:migrate");
  console.log("  4. pnpm dev");
}

main();
