#!/usr/bin/env python3
"""
Easy-install / deployment script for mkindayzir.

Single-process architecture (target):
- Backend: FastAPI served by the `mkindayzir` CLI; `mkindayzir start` runs uvicorn
  on port 3000 serving the API + the built Vite frontend.
- DB: PostgreSQL (asyncpg) for every mode. SQLite is legacy import-only.
- Migrations: Alembic. First run: `alembic upgrade head`, then `mkindayzir setup admin`.
- Docker: a SINGLE root Dockerfile builds the frontend and runs FastAPI on :3000.
  docker/docker-compose.yml defines one `app` service plus an optional `postgres`
  service under `profiles: [team]`.
- Session cookie: mkindayzir_session.

Stdlib-only (no pip deps) so it runs on stock Python 3.11+ after a plain download.

Subcommands:
  local    Personal-mode install without Docker (venv + pip install -e ./backend).
  deploy   Docker-based deploy for personal / team / enterprise modes.

Note: the admin command is `mkindayzir setup admin --email ... --password ...`
(the `setup` Click group with an `admin` subcommand).
"""

import argparse
import base64
import os
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path


class Colors:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    CYAN = "\033[96m"
    WHITE = "\033[97m"
    UNDERLINE = "\033[4m"

    @classmethod
    def ok(cls, text):
        return f"{cls.GREEN}{text}{cls.RESET}"

    @classmethod
    def err(cls, text):
        return f"{cls.RED}{text}{cls.RESET}"

    @classmethod
    def warn(cls, text):
        return f"{cls.YELLOW}{text}{cls.RESET}"

    @classmethod
    def info(cls, text):
        return f"{cls.CYAN}{text}{cls.RESET}"

    @classmethod
    def header(cls, text):
        return f"\n{cls.BOLD}{cls.CYAN}── {text} {cls.RESET}"


def die(message):
    print(Colors.err(f"✗ {message}"))
    sys.exit(1)


def generate_secret(byte_len=32):
    return base64.urlsafe_b64encode(secrets.token_bytes(byte_len)).decode("utf-8").rstrip("=")


def project_root():
    return Path(__file__).resolve().parent.parent


def docker_dir():
    return project_root() / "docker"


def run_command(cmd, cwd=None, env=None, check=True, capture=True):
    merged_env = {**os.environ}
    if env:
        merged_env.update(env)
    print(Colors.dim(f"  $ {' '.join(cmd)}"))
    try:
        return subprocess.run(
            cmd,
            cwd=str(cwd) if cwd else None,
            env=merged_env,
            capture_output=capture,
            text=True,
            check=check,
        )
    except subprocess.CalledProcessError as exc:
        out = exc.stderr or exc.stdout or ""
        die(f"Command failed: {' '.join(cmd)}\n{out[-1500:]}")


def command_exists(cmd):
    return shutil.which(cmd) is not None


def print_banner(mode, domain):
    print(
        f"\n{Colors.BOLD}{Colors.CYAN}"
        "====== Mkindayzir — Easy Install / Deploy ======\n"
        f"  Mode:   {mode.upper()}\n"
        f"  Domain: {domain or 'localhost'}\n"
        f"{Colors.RESET}"
    )


def build_env_content(mode, domain, db_password):
    session_secret = generate_secret()
    encryption_key = generate_secret()

    if mode == "personal":
        provider = "postgres"
        database_url = "postgresql+asyncpg://mkindayzir:CHANGE_ME@127.0.0.1:5432/mkindayzir"
        postgres_block = ""
    else:
        provider = "postgres"
        database_url = (
            f"postgresql+asyncpg://mkindayzir:{db_password}@postgres:5432/mkindayzir"
        )
        postgres_block = (
            "\n# PostgreSQL (consumed by the `postgres` compose service)\n"
            f"POSTGRES_USER=mkindayzir\n"
            f"POSTGRES_PASSWORD={db_password}\n"
            f"POSTGRES_DB=mkindayzir\n"
        )

    base_url = (
        "http://localhost:3000"
        if mode == "personal"
        else (domain if domain.startswith("http") else f"https://{domain}")
    )

    return f"""# Auto-generated by easy-install.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
MKINDAYZIR_MODE={mode}
PORT=3000
BASE_URL={base_url}

# Database
DATABASE_PROVIDER={provider}
DATABASE_URL={database_url}
DATA_DIR=./data
{postgres_block}
# Security
SESSION_SECRET={session_secret}
ENCRYPTION_KEY={encryption_key}
SESSION_COOKIE_NAME=mkindayzir_session
SESSION_MAX_AGE=86400

# Application
NODE_ENV=production
LOG_LEVEL=info
"""


def write_env_file(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(Colors.ok(f"✓ Wrote .env -> {path}"))


def check_python():
    if sys.version_info < (3, 11):
        die(f"Python 3.11+ is required (found {sys.version.split()[0]}).")


def check_docker():
    print(Colors.header("CHECKING PREREQUISITES (Docker)"))
    if not command_exists("docker"):
        die("Docker is not installed. Install it from https://docs.docker.com/get-docker/")

    result = subprocess.run(["docker", "compose", "version"], capture_output=True, text=True)
    if result.returncode != 0:
        die(
            "The Docker Compose plugin is missing. Install it via the Docker plugin "
            "(https://docs.docker.com/compose/install/) -- `docker compose version` must succeed."
        )
    print(Colors.ok(f"✓ docker: {result.stdout.strip().splitlines()[0]}"))

    info = subprocess.run(["docker", "info"], capture_output=True, text=True)
    if info.returncode != 0:
        die("Docker daemon is not running. Start Docker and retry.")
    print(Colors.ok("✓ Docker daemon is reachable"))


def cmd_local(args):
    mode = "personal"
    email = args.email
    password = args.password or generate_secret(16)
    root = project_root()

    print_banner(mode, "")
    print(Colors.info(f"Project root: {root}"))
    check_python()

    venv_dir = root / ".venv"
    venv_bin = venv_dir / "bin"
    if sys.platform == "win32":
        venv_bin = venv_dir / "Scripts"

    print(Colors.header("CREATING VIRTUALENV & INSTALLING"))
    if venv_dir.exists():
        print(Colors.warn(f"Reusing existing venv at {venv_dir}"))
    else:
        run_command([sys.executable, "-m", "venv", str(venv_dir)])
        print(Colors.ok(f"✓ Created venv at {venv_dir}"))

    pip = str(venv_bin / "pip")
    run_command([pip, "install", "--upgrade", "pip"])
    print(Colors.info("Installing backend (editable) -- provides `mkindayzir` and `alembic`..."))
    run_command([pip, "install", "-e", "./backend"])

    (root / "data").mkdir(parents=True, exist_ok=True)

    print(Colors.header("WRITING CONFIG"))
    write_env_file(root / ".env", build_env_content(mode=mode, domain="", db_password=""))

    print(Colors.header("RUNNING MIGRATIONS"))
    run_command([str(venv_bin / "alembic"), "upgrade", "head"], cwd=root / "backend")
    print(Colors.ok("✓ Migrations applied"))

    print(Colors.header("CREATING ADMIN"))
    run_command(
        [
            str(venv_bin / "mkindayzir"), "setup", "admin",
            "--email", email,
            "--password", password,
            "--name", "Admin",
        ]
    )
    print(Colors.ok("✓ Admin created"))

    print(Colors.header("DONE -- PERSONAL MODE (LOCAL)"))
    print(f"  {Colors.BOLD}URL:{Colors.RESET}       http://localhost:3000")
    print(f"  {Colors.BOLD}Email:{Colors.RESET}     {email}")
    print(f"  {Colors.BOLD}Password:{Colors.RESET}  {password}")
    print(f"  {Colors.BOLD}Mode:{Colors.RESET}      Personal (PostgreSQL, single process on :3000)")
    print()
    print(Colors.info("Start the server with:"))
    print(f"     {Colors.CYAN}source .venv/bin/activate && mkindayzir start{Colors.RESET}")
    print(f"  or simply: {Colors.CYAN}.venv/bin/mkindayzir start{Colors.RESET}")
    print()


def compose_file_path():
    p = docker_dir() / "docker-compose.yml"
    if not p.exists():
        die(f"Compose file not found: {p}")
    return p


def compose_base_cmd(compose_file, profile):
    cmd = ["docker", "compose", "-f", str(compose_file)]
    if profile:
        cmd += ["--profile", profile]
    return cmd


def cmd_deploy(args):
    mode = args.mode
    domain = args.domain or ""
    email = args.email
    db_password = args.db_password or generate_secret(24)
    root = project_root()

    print_banner(mode, domain)
    print(Colors.info(f"Project root: {root}"))

    check_docker()

    if mode in ("team", "enterprise") and not domain:
        print(Colors.warn("No --domain supplied; TLS/reverse-proxy guidance assumes a domain."))

    print(Colors.header("WRITING CONFIG"))
    env_path = docker_dir() / ".env"
    write_env_file(
        env_path,
        build_env_content(mode=mode, domain=domain, db_password=db_password),
    )

    compose_file = compose_file_path()
    profile = "team" if mode in ("team", "enterprise") else None
    base = compose_base_cmd(compose_file, profile)

    print(Colors.header(f"BUILDING & STARTING ({mode.upper()})"))
    run_command(base + ["build"])
    print(Colors.ok("✓ Images built"))
    run_command(base + ["up", "-d"])
    print(Colors.ok("✓ Services started"))

    wait_for_health()

    print(Colors.header("RUNNING MIGRATIONS"))
    run_command(base + ["exec", "-T", "app", "alembic", "upgrade", "head"])
    print(Colors.ok("✓ Migrations applied"))

    print(Colors.header("CREATING ADMIN"))
    admin_password = generate_secret(16)
    run_command(
        base
        + ["exec", "-T", "app", "mkindayzir", "setup", "admin",
           "--email", email, "--password", admin_password, "--name", "Admin"]
    )
    print(Colors.ok("✓ Admin created"))

    url = (
        (domain if domain.startswith("http") else f"https://{domain}")
        if domain
        else "http://localhost:3000"
    )
    print(Colors.header("DEPLOYMENT COMPLETE"))
    print(f"  {Colors.BOLD}URL:{Colors.RESET}       {Colors.UNDERLINE}{url}{Colors.RESET}")
    print(f"  {Colors.BOLD}Email:{Colors.RESET}     {email}")
    print(f"  {Colors.BOLD}Password:{Colors.RESET}  {admin_password}")
    print(f"  {Colors.BOLD}Mode:{Colors.RESET}      {mode.capitalize()} (single process on :3000)")
    print()
    print(Colors.info("Management:"))
    print(f"  Logs:    {Colors.CYAN}{' '.join(base)} logs -f{Colors.RESET}")
    print(f"  Stop:    {Colors.CYAN}{' '.join(base)} down{Colors.RESET}")
    print(f"  Restart: {Colors.CYAN}{' '.join(base)} restart{Colors.RESET}")
    print()


def wait_for_health(timeout=300, port=3000):
    print(Colors.header("WAITING FOR HEALTH (http://localhost:3000/api/health)"))
    start = time.time()
    while time.time() - start < timeout:
        try:
            req = urllib.request.Request(f"http://localhost:{port}/api/health")
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 200:
                    print(Colors.ok("\n✓ App is healthy"))
                    return
        except (urllib.error.URLError, OSError):
            pass
        elapsed = int(time.time() - start)
        sys.stdout.write(f"\r{Colors.DIM}  waiting... {elapsed}s{Colors.RESET}")
        sys.stdout.flush()
        time.sleep(5)
    print()
    die("Health check timed out. Inspect logs with: docker compose -f docker/docker-compose.yml ps")


def build_parser():
    parser = argparse.ArgumentParser(
        prog="easy-install.py",
        description="One-command install/deploy for mkindayzir (FastAPI + Vite SPA, single process on :3000).",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    local = sub.add_parser("local", help="Install personal mode locally (venv + pip, no Docker).")
    local.add_argument("--mode", default="personal", const="personal", nargs="?",
                       choices=["personal"], help="Local install is personal mode.")
    local.add_argument("--email", required=True, help="Admin email address.")
    local.add_argument("--password", default=None,
                       help="Admin password (auto-generated and printed if omitted).")
    local.set_defaults(func=cmd_local)

    deploy = sub.add_parser("deploy", help="Deploy via Docker Compose (personal/team/enterprise).")
    deploy.add_argument("--mode", required=True, choices=["personal", "team", "enterprise"],
                        help="Mode selection (database is PostgreSQL in all modes).")
    deploy.add_argument("--email", required=True, help="Admin email address.")
    deploy.add_argument("--domain", default="", help="Public domain (team/enterprise).")
    deploy.add_argument("--db-password", default=None,
                        help="PostgreSQL password (auto-generated if omitted).")
    deploy.set_defaults(func=cmd_deploy)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
